spring:
  application:
    name: sfz-template-api
  config:
    import: "optional:configserver:http://admin:admin@localhost:8761/config"
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@localhost:1521:DBIC
    username: admdba006
    password: admdba006

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
    enabled: true

sefaz:
  logging:
    logstash:
      enabled: true
      host: log.sefaz.al.gov.br

